name: Publish Release Build

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build the Docker container image
        run: docker build -t docker.pkg.github.com/emrbear/trip-reporter/trip-reporter:${GITHUB_REF} .

      - name: Push the image to GPR
        run: |
          docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
          docker push docker.pkg.github.com/emrbear/trip-reporter/trip-reporter:${GITHUB_REF}
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

